### ISSUE TITLE
help

### ISSUE THREAD

**Issue by donggua2096** [Hans0924/fsd_java#2]
I have a game server. The password and account number stored in it is a TXT document. How can I bind it to the account and password of the forum? As long as someone registers for the forum, the game server also has his account, and he can play

**Comment by Hans0924** [comment]
Basically, you have two choices:

- Implementing a customized authentication and identity system in FSD Server.

- Using some scripts to sync your forum users and password to FSD's cert.txt, while FSD will reload cert if the file has changed.

**Comment by donggua2096** [comment]
Are you Chinese?

**Comment by donggua2096** [comment]
你是中国人吗？
&nbsp;


生活
wangxuan244@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hanshuo Zeng"<notifications@github.com&gt;; 
发送时间: 2020年9月23日(星期三) 下午5:40
收件人: "Hans0924/fsd_java"<fsd_java@noreply.github.com&gt;; 
抄送: "A-----1a"<2096155326@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Hans0924/fsd_java] help (#2)





 Basically, you have two choices:- Implementing a customized authentication and identity system in FSD Server.- Using some scripts to sync your forum users and password to FSD's cert.txt, while FSD will reload cert if the file has changed.2020年9月23日 16:53，donggua2096 <notifications@github.com&gt;写道：
 I have a game server. The password and account number stored in it is a TXT document. How can I bind it to the account and password of the forum? As long as someone registers for the forum, the game server also has his account, and he can play
